version: '3.8'

services:
  frontend:
    image: node:14
    container_name: my_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

  backend:
    image: node:14
    container_name: my_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start



Explanation:
This example defines two services, "frontend" and "backend," both using the Node.js 14 image.
Each service has its own container name, and they expose ports 3000 and 5000 for the frontend and backend, respectively.
The "./frontend" and "./backend" directories on the host machine are mounted into the corresponding containers as "/usr/src/app".
The working directory inside each container is set to "/usr/src/app".
The "npm start" command is used to start the React frontend and Express backend applications.
